version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: shopper-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"

volumes:
  db_data:
